### ISSUE TITLE
Need a example

### ISSUE THREAD

**Issue by etiennegautier** [gkozlenko/node-media-server#2]
Hi gkozlenko,

I created a m3u8 with ffmpeg, so I have my .ts files and my m3u8 playlist but in which folder should I put it to stream with the server?

Thank you for your work!

**Comment by gkozlenko** [comment]
Hi etiennegautier,

You don't need to create .m3u8 and .ts files. You just need to play your MP4 files into media folder and the server will generate .m3u8 and .ts files by its own. Please ensure that your MP4 files have H.264/H.265 video codecs and AAC audio codecs.

Thank you.

**Comment by etiennegautier** [comment]
Great, it works perfectly! 

Thanks
