### ISSUE TITLE
How about the performance?

### ISSUE THREAD

**Issue by qiufeihai** [gkozlenko/node-media-server#3]
How about the performance? Can this use for video  site ?

**Comment by gkozlenko** [comment]
It's an interesting question. On the one hand I was concerned about performance when I developed it. Media Server utilises all server threads (and you can change number of workers using the `workers .web.count` parameter). On the other hand it's JavaScript, so it can't be as performance as other programming languages as GoLang, Java or C++.

**Comment by qiufeihai** [comment]
Have you ever used it in a production environment

**Comment by gkozlenko** [comment]
No, I haven't used it on a production environment. It's a kind of a pet project.
