### ISSUE TITLE
failed to load video

### ISSUE THREAD

**Issue by cidrak** [gkozlenko/node-media-server#4]
video length error in more than one hour of view.
video less than an hour long works very well.

-- sorry i can't write english

**Comment by gkozlenko** [comment]
Hi Cidrak,

Could you please attach an error which the media server shows? And it would be very helpful if you could send me a link to the problem video to test.

Thank you.

**Comment by cidrak** [comment]
hello!
the server does not show me any errors.
here is the video link: [https://drive.google.com/file/d/1MUlZLIX6jkPRYlkwHFWjNZHQpV1tzkpt/view?usp=sharing](https://drive.google.com/file/d/1MUlZLIX6jkPRYlkwHFWjNZHQpV1tzkpt/view?usp=sharing)

video duration: 02:16:41

after moving on to 01:53:41 ...
at 01:54:46, the video no longer works.

thanks!

**Comment by gkozlenko** [comment]
Hello,

I've just checked this video - everything works fine. Could you also specify on which platform do you launch the video server (Linux, Windows, Mac)? And which video player do you use?

Also try to download the latest version of the media server and try to use JWPlayer to play the video: https://www.jwplayer.com/developers/stream-tester/

Thank you.

**Comment by cidrak** [comment]
**Problem Solved!**

Operating system in use: Windows
Player in use: [DPlayer](https://github.com/MoePlayer/DPlayer)
Additional: [hls.js](https://github.com/video-dev/hls.js/) library.

I also did the test with "[Jwplayer](https://www.jwplayer.com/developers/stream-tester/)" and everything worked perfectly.
I found that the error is in the "[hls.js](https://github.com/video-dev/hls.js/)" library.

**Thank You Very Much** for your Attention!
