### ISSUE TITLE
Can this project be used as a DRM license server?

### ISSUE THREAD

**Issue by mukesh-610** [gkozlenko/node-media-server#5]
I'm not really experienced with DRM, so sorry in advance for any mistakes.

I need to set up a DRM-protected video streaming website, and I have a few questions.
    - Can I package and encrypt videos to be hosted on the server?
    - Can the server be used to distribute licenses to clients, for decrypting the encrypted videos? If not, are there any open source projects which do that?

Thanks in advance,
Mukesh

**Comment by mukesh-610** [comment]
I've realized it cannot be done. Sorry for taking up your time.

**Comment by Bessonov** [comment]
@mukesh-610 hey, did you found a solution?

**Comment by MukeshS-hexaware** [comment]
@Bessonov No, sorry, I've given up on that.
