### ISSUE TITLE
How does this work?!

### ISSUE THREAD

**Issue by theraw** [gkozlenko/node-media-server#6]
Hi,

I have some question about how does this script work? 

https://github.com/gkozlenko/node-media-server/issues/2 you say "Please ensure that your MP4 files have H.264/H.265 video codecs and AAC audio codecs.", 

This makes me think that this script doesn't come with any kind of "encoding" like convert mkv/mp4 or change video/audio codec but all it does is "convert" mp4 videos to hls format which shouldn't take much resources to do i mean based on what way you do i'm talking about smth like
```
ffmpeg -i video.mp4 -codec copy -start_number 0 -hls_playlist_type vod -hls_time 3 -hls_list_size 0 -f hls play.m3u8
```
is this right?!

if that is what it does what happens if some user watches one video and after you generated `.m3u8` for that video? do you save the hls files/m3u8 which was generated from first view and provide them to some other user or do you generate a new m3u8/hls i mean converting video everytime a new user tries to open and watch the same video?!

**Comment by gkozlenko** [comment]
Hi,

You are right, this media server doesn't do any encoding, it just generates `.ts` and `.m3u8` files for viewers. It does it on the fly - without caching for new viewers. It only caches some metadata to parse MP4 files faster.

The media server doesn't use the `ffmpeg` binaries - everything is written in JavaScript.

Thank you.

**Comment by theraw** [comment]
@gkozlenko thanks for info adding cache will be better ofcourse for production usage

i'm closing this since i have no issue just asking
