### ISSUE TITLE
Remote URL?

### ISSUE THREAD

**Issue by valascus** [gkozlenko/node-media-server#8]
Hi! Is there a way to provide a remote url instead of a path?
For example, i have on my website, 
EXTERNAL_IP:80/F/File/video.mp4 and i want to stream that file on another server, because my "hosting" server has no hls. Could that be done?

**Comment by gkozlenko** [comment]
Hi @valascus,

Unfortunately it's not supported now and I don't have any plans about adding this feature it in the future.

Thank you.
